# Generated by Django 6.0 on 2026-03-29 13:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_doctor_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patients',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
